# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |  # use pipenv to install dependencies
              sudo pip install pipenv
              pipenv install requirements.txt
      -save_cache:
      key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
        paths:
          - ".venv"
          - "/usr/local/bin"
          - "/usr/local/lib/python3.6/site-packages"

    # Step 3: run tests
      - run:
         name: run tests
         command: |
           pipenv run python test/unit_test.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1